### ISSUE TITLE
Where is the HybridLLMPlanner script available?

### ISSUE THREAD

**Issue by hairuoliu1** [mh0797/interPlan#1]

**Comment by mh0797** [comment]
Hi @hairuoliu1,
we implemented all baselines in a fork of the [tuplan_garage](https://github.com/autonomousvision/tuplan_garage).
We are currently in the process of releasing this code as well and contributing it to the official repository.

I will follow up here once the code is available.

**Comment by mh0797** [comment]
Quick follow-up: until the final release, you can find the code for the LLM-Planners here: https://github.com/mh0797/tuplan_garage_llm_baselines

**Comment by richie-live** [comment]
> Quick follow-up: until the final release, you can find the code for the LLM-Planners here: https://github.com/mh0797/tuplan_garage_llm_baselines


Does this code work, and how to run it

**Comment by mh0797** [comment]
Hi,
it does work. Simply install the repository. Then you should be able to run the planners in the same way as all remaining planners from tuplan_garage.
