### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by invinciblenuonuo** [mh0797/interPlan#10]
Thank you for your contributions.
Could you please clarify where the log data for the interplan10 benchmark originated? It appears to be different from the nuplan v1.1 val Split utilized in val14.

**Comment by mh0797** [comment]
The logs are part of the nuPlan test split. They were selected manually to make sure they cover diverse map layouts which are suitable for constructing a variety of challenging scenarios. They are not taken from val14. 
Thus, if you want to run interPlan, it is necessary to download the nuPlan test split.
