### ISSUE TITLE
Question about extra agents

### ISSUE THREAD

**Issue by invinciblenuonuo** [mh0797/interPlan#11]
Hello Marcel, 

I'm wondering if it's possible to specify a destination or goal for the extra_agents when modifying a scenario. Is there a way to make them move towards a particular point?

**Comment by mh0797** [comment]
Hi @invinciblenuonuo,

This feature does unfortunately not exist. The extra_agents are controlled by idm policies that follow the current lane. 
If you want them to move to a certain location, you need to adapt the route generation used in [this function](https://github.com/mh0797/interPlan/blob/main/interplan/planning/simulation/observation/idm/idm_modified_agents_builder.py#L108)
