### ISSUE TITLE
question about hydra

### ISSUE THREAD

**Issue by jessapinkman** [mh0797/interPlan#4]
hi, @mh0797 

I am trying to test the checkpoints of my trained model on the interplan benchmark, and I build my own scripts as follows:

`cwd=$(pwd)
CKPT_ROOT="$cwd/checkpoints"

PLANNER=$1
BUILDER=$2
FILTER=$3
CKPT=$4
VIDEO_SAVE_DIR=$5

python run_simulation.py \
    +simulation=default_interplan_benchmark \
    planner=$PLANNER \
    scenario_builder=$BUILDER \
    scenario_filter=$FILTER \
    worker=sequential \
    verbose=true \
    experiment_uid="my_planner/$FILTER" \
    planner.pluto_planner.render=false \
    planner.pluto_planner.planner_ckpt="$CKPT_ROOT/$CKPT" \
    +planner.pluto_planner.save_dir=$VIDEO_SAVE_DIR \
    hydra.searchpath="[\
    pkg://interplan.planning.script.config.common,\
    pkg://interplan.planning.script.config.simulation,\
    pkg://interplan.planning.script.experiments,\
    pkg://nuplan.planning.script.config.common,\
    pkg://nuplan.planning.script.config.simulation,\
    pkg://nuplan.planning.script.experiments\
    ]"`

but I got the following errors, it seems like something wrong with the scenario builder. Because in nuplan bechmark, scenario token is like "09ca86cc9ae65428", but in interplan, scenario token is like "d480a5d2b0fe5fe6-dlgloa":

Error executing job with overrides: ['+simulation=default_interplan_benchmark', 'planner=pluto_planner', 'scenario_builder=interplan', 'scenario_filter=interplan10', 'worker=sequential', 'verbose=true', 'experiment_uid=pluto_planner/interplan10', 'planner.pluto_planner.render=false', 'planner.pluto_planner.planner_ckpt=/home/jessapinkman/src/pluto/checkpoints/pluto_1M_aux_cil.ckpt', '+planner.pluto_planner.save_dir=null']
Traceback (most recent call last):
  File "/home/jessapinkman/src/pluto/run_simulation.py", line 142, in <module>
    main()
  File "/root/anaconda3/envs/plantf/lib/python3.9/site-packages/hydra/main.py", line 49, in decorated_main
    _run_hydra(
  File "/root/anaconda3/envs/plantf/lib/python3.9/site-packages/hydra/_internal/utils.py", line 367, in _run_hydra
    run_and_report(
  File "/root/anaconda3/envs/plantf/lib/python3.9/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/root/anaconda3/envs/plantf/lib/python3.9/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/root/anaconda3/envs/plantf/lib/python3.9/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "/root/anaconda3/envs/plantf/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 110, in run
    _ = ret.return_value
  File "/root/anaconda3/envs/plantf/lib/python3.9/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/root/anaconda3/envs/plantf/lib/python3.9/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/jessapinkman/src/pluto/run_simulation.py", line 133, in main
    run_simulation(cfg=cfg)
  File "/home/jessapinkman/src/pluto/run_simulation.py", line 83, in run_simulation
    runners = build_simulations(
  File "/home/jessapinkman/src/nuplan-devkit/nuplan/planning/script/builders/simulation_builder.py", line 70, in build_simulations
    scenarios = scenario_filter.get_scenarios()
  File "/home/jessapinkman/src/nuplan-devkit/nuplan/common/utils/distributed_scenario_filter.py", line 85, in get_scenarios
    scenario_filter = build_scenario_filter(cfg=self._cfg.scenario_filter)
  File "/home/jessapinkman/src/nuplan-devkit/nuplan/planning/script/builders/scenario_filter_builder.py", line 37, in build_scenario_filter
    raise RuntimeError(
**RuntimeError: Expected all scenario tokens to be 16-character strings. Your shell may strip quotes causing hydra to parse a token as a float, so consider passing them like scenario_filter.scenario_tokens='["595322e649225137", ...]'**

I would appreciate it if you could help me to fix it.

**Comment by mh0797** [comment]
Hi @jessapinkman,
I guess you are trying to run the `run_simulation.py` script from nuPlan. However, in order to run interPlan, you need to use the respective script from [interplan](https://github.com/mh0797/interPlan/blob/main/interplan/planning/script/run_simulation.py). The interface is exactly the same as for nuPlan.
Let me know if this solves your problem.

**Comment by jessapinkman** [comment]
hi, @mh0797 

I solved the above issue, but the new issue occurred as the same as   [issue3](https://github.com/mh0797/interPlan/issues/3). And here is my worksapce directory, after pip all the requirements, do you mean I need to merge the entire interplan with my own repo (put both in one workspace)?

![image](https://github.com/user-attachments/assets/532252ce-221a-46ca-96b5-f1d38569f3f6)

**Comment by mh0797** [comment]
Hi @jessapinkman,
Can you describe what exactly your issue is? If it is that no scenarios are found for evaluation, you might have to download the nuPlan test split.

Regarding workspace organization: There is no need to merge your code into interPlan. You can simply have them next to each other. Your workspace could look as follows:
```
workspace_folder
├── nuplan-devkit              - the official nuPlan devkit (needed for interPlan)
├── interplan                  - interPlan code
└── your-planner-code          - your code goes here
```

**Comment by jessapinkman** [comment]
hi, @mh0797 

Yes, when I ran interplan10 benchmark, I met the same issues as [issue3](the same as https://github.com/mh0797/interPlan/issues/3), that is no scenarios are found for evaluation.:
![image](https://github.com/user-attachments/assets/8e6d5cab-6b65-4efb-944a-2c2162355c5c)


 Of course I downloaded and unzipped the test splits, and I could validate my model in nuplan random14-benchmark well. And my dataset setup looks as follows:

nuplan
├── exp         
├── dataset       
---------└── trainval
---------└── test
---------└── mini

**Comment by mh0797** [comment]
Hi,
The test logs belong to the trainval folder. Otherwise, the scenario-builder won't find them.
Don't worry about them getting mixed up with the trainval logs: the nuPlan splitter contains a list of log-names for training and testing. Thus, they can be in the same directory without being mixed.

**Comment by jessapinkman** [comment]
Hahaha, it worked, I may have figured out why I could run random14_benchmark but not val14_benchmark.

Also, after I get the interplan results, I may have some details to ask you, so could you keep this issue open? I guarantee it won't last too long. Of course, if you feel that this is causing you trouble, you can simply turn it off.

Much appreciation for your kind help :)

**Comment by mh0797** [comment]
Happy to hear.
I would close this issue for now. I highly encourage you to open a new issue if you have any questions about the results.
This way, finding this issue is much easier for other users with the same problem. 
If you have a question related to this issue here, then feel free to simply re-open it :)

**Comment by jessapinkman** [comment]
hi, @mh0797 

Did you evaluate the results of the other two baselines on the interplan benchmark (i.e., [RasterModel](https://github.com/motional/nuplan-devkit) and [Plantf](https://github.com/jchengai/planTF))?  Also, I noticed that you found a wrong token in our config, so do I just need to replace "f8684ea2cf1c512b-s0,f8684ea2cf1c512b-s1" with "9e7581ef72155c9f" in the config?

**Comment by mh0797** [comment]
Hi @jessapinkman,
(1) We did not evaluate these baselines, but it should be straightforward to run them with the code provided.
(2) The easiest would be to pull the latest commit from our interPlan repo. Alternatively, you can replace `f8684ea2cf1c512b-s0` with `9e7581ef72155c9f-0` and `f8684ea2cf1c512b-s1` with `9e7581ef72155c9f-s1`.

**Comment by jessapinkman** [comment]
Alright. Thanks for your rapid replay !

**Comment by jessapinkman** [comment]
hi, @mh0797 

I am sorry to disturb you again. When I get the visualization scene through nuboard, the color scheme is not very good, as shown below:
![image](https://github.com/user-attachments/assets/908b134f-eb4d-411f-bcfb-08e623c910f1)

How can I configure nuboard to get a rendering scene like yours?
![image](https://github.com/user-attachments/assets/5183e283-5099-4b86-8f9f-835ae04cf827)

**Comment by mh0797** [comment]
Hi @jessapinkman,

unfortunately, its not possible to change the colors in a config.

However, you can change the colors by directly adapting them in the nuPlan code.
In [this](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/nuboard/style.py#L58) file, you can adapt the colors for the ego veicle, the surrounding vehicles etc.

Best
Marcel

**Comment by jessapinkman** [comment]
@mh0797 
Alright, I mean can you share your colorway in [this ](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/nuboard/style.py#L58)script?

**Comment by mh0797** [comment]
We used the following:

```
simulation_tile_trajectory_style: Dict[str, Any] = {
"ego": {"line_color": "#e38c47", "line_alpha": 1.0, "line_width": 2},
"expert_ego": {"line_color": "#7030a0", "line_alpha": 1.0, "line_width": 2}
}
```

```
simulation_tile_agent_style: Dict[str, Any] = {
"ego": {"fill_color": "#e38c47", "fill_alpha": 1.0, "line_color": "#000000", "line_width": 1},
"vehicles": {"fill_color": "#699cdb", "fill_alpha": 1.0, "line_color": "#000000", "line_width": 0.5},
"pedestrians": {"fill_color": "#b0e685", "fill_alpha": 1.0, "line_color": "#000000", "line_width": 1},
"bicycles": {"fill_color": "#FF4D4D", "fill_alpha": 0.5, "line_color": "#FF4D4D", "line_width": 1},
"genericobjects": {"fill_color": "#AE4DFF", "fill_alpha": 0.5, "line_color": "#AE4DFF", "line_width": 1},
"traffic_cone": {"fill_color": "#ed2a2a", "fill_alpha": 1.0, "line_color": "#ed2a2a", "line_width": 1},
"barrier": {"fill_color": "#FFCC4D", "fill_alpha": 0.5, "line_color": "#FFCC4D", "line_width": 1},
"czone_sign": {"fill_color": "#00f6ff", "fill_alpha": 0.5, "line_color": "#00f6ff", "line_width": 1},
 }
```
```
 simulation_map_layer_color: Dict[SemanticMapLayer, Any] = {
SemanticMapLayer.LANE: {"fill_color": "#CCCCCC", "fill_color_alpha": 1.0, "line_color": "#FFFFFF"},
SemanticMapLayer.WALKWAYS: {"fill_color": "#7e772e", "fill_color_alpha": 0.5, "line_color": "#7e772e"},
SemanticMapLayer.CARPARK_AREA: {"fill_color": "#ff7f00", "fill_color_alpha": 0.5, "line_color": "#ff7f00"},
SemanticMapLayer.PUDO: {"fill_color": "#AF75A7", "fill_color_alpha": 0.3, "line_color": "#AF75A7"},
SemanticMapLayer.INTERSECTION: {"fill_color": "#CCCCCC", "fill_color_alpha": 1.0, "line_color": "#CCCCCC"},
SemanticMapLayer.STOP_LINE: {"fill_color": "#DF7061", "fill_color_alpha": 0.5, "line_color": "#FF0101"},
SemanticMapLayer.CROSSWALK: {"fill_color": "#B5B5B5", "fill_color_alpha": 0.3, "line_color": "#B5B5B5"},
SemanticMapLayer.ROADBLOCK: {"fill_color": "#CCCCCC", "fill_color_alpha": 0.2, "line_color": "#CCCCCC"},
SemanticMapLayer.BASELINE_PATHS: {"line_color": "#FFFFFF", "line_color_alpha": 1.0},
SemanticMapLayer.LANE_CONNECTOR: {"line_color": "#FFFFFF", "line_color_alpha": 1.0},
 }
```


also make sure to set the background color [here](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/nuboard/style.py#L44) to `background_color": "#FFFFFF`

**Comment by happy-yan** [comment]
> hi, [@mh0797](https://github.com/mh0797)
> 
> I am trying to test the checkpoints of my trained model on the interplan benchmark, and I build my own scripts as follows:
> 
> `cwd=$(pwd) CKPT_ROOT="$cwd/checkpoints"
> 
> PLANNER=$1 BUILDER=$2 FILTER=$3 CKPT=$4 VIDEO_SAVE_DIR=$5
> 
> python run_simulation.py +simulation=default_interplan_benchmark planner=$PLANNER scenario_builder=$BUILDER scenario_filter=$FILTER worker=sequential verbose=true experiment_uid="my_planner/$FILTER" planner.pluto_planner.render=false planner.pluto_planner.planner_ckpt="$CKPT_ROOT/$CKPT" +planner.pluto_planner.save_dir=$VIDEO_SAVE_DIR hydra.searchpath="[ pkg://interplan.planning.script.config.common, pkg://interplan.planning.script.config.simulation, pkg://interplan.planning.script.experiments, pkg://nuplan.planning.script.config.common, pkg://nuplan.planning.script.config.simulation, pkg://nuplan.planning.script.experiments ]"`
> 
> but I got the following errors, it seems like something wrong with the scenario builder. Because in nuplan bechmark, scenario token is like "09ca86cc9ae65428", but in interplan, scenario token is like "d480a5d2b0fe5fe6-dlgloa":
> 
> Error executing job with overrides: ['+simulation=default_interplan_benchmark', 'planner=pluto_planner', 'scenario_builder=interplan', 'scenario_filter=interplan10', 'worker=sequential', 'verbose=true', 'experiment_uid=pluto_planner/interplan10', 'planner.pluto_planner.render=false', 'planner.pluto_planner.planner_ckpt=/home/jessapinkman/src/pluto/checkpoints/pluto_1M_aux_cil.ckpt', '+planner.pluto_planner.save_dir=null'] Traceback (most recent call last): File "/home/jessapinkman/src/pluto/run_simulation.py", line 142, in main() File "/root/anaconda3/envs/plantf/lib/python3.9/site-packages/hydra/main.py", line 49, in decorated_main _run_hydra( File "/root/anaconda3/envs/plantf/lib/python3.9/site-packages/hydra/_internal/utils.py", line 367, in _run_hydra run_and_report( File "/root/anaconda3/envs/plantf/lib/python3.9/site-packages/hydra/_internal/utils.py", line 214, in run_and_report raise ex File "/root/anaconda3/envs/plantf/lib/python3.9/site-packages/hydra/_internal/utils.py", line 211, in run_and_report return func() File "/root/anaconda3/envs/plantf/lib/python3.9/site-packages/hydra/_internal/utils.py", line 368, in lambda: hydra.run( File "/root/anaconda3/envs/plantf/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 110, in run _ = ret.return_value File "/root/anaconda3/envs/plantf/lib/python3.9/site-packages/hydra/core/utils.py", line 233, in return_value raise self._return_value File "/root/anaconda3/envs/plantf/lib/python3.9/site-packages/hydra/core/utils.py", line 160, in run_job ret.return_value = task_function(task_cfg) File "/home/jessapinkman/src/pluto/run_simulation.py", line 133, in main run_simulation(cfg=cfg) File "/home/jessapinkman/src/pluto/run_simulation.py", line 83, in run_simulation runners = build_simulations( File "/home/jessapinkman/src/nuplan-devkit/nuplan/planning/script/builders/simulation_builder.py", line 70, in build_simulations scenarios = scenario_filter.get_scenarios() File "/home/jessapinkman/src/nuplan-devkit/nuplan/common/utils/distributed_scenario_filter.py", line 85, in get_scenarios scenario_filter = build_scenario_filter(cfg=self._cfg.scenario_filter) File "/home/jessapinkman/src/nuplan-devkit/nuplan/planning/script/builders/scenario_filter_builder.py", line 37, in build_scenario_filter raise RuntimeError( **RuntimeError: Expected all scenario tokens to be 16-character strings. Your shell may strip quotes causing hydra to parse a token as a float, so consider passing them like scenario_filter.scenario_tokens='["595322e649225137", ...]'**
> 
> I would appreciate it if you could help me to fix it.


This is my vscode debug json. I got a error. 

        {
            "name": "Run inter Planner",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/run_simulation.py",
            "console": "integratedTerminal",
            "justMyCode": false, 
            "env": {
                "HYDRA_SEARCHPATH": "'pkg://interplan.planning.script.config.common','pkg://interplan.planning.script.config.simulation','pkg://interplan.planning.script.config.experiments','pkg://nuplan.planning.script.config.common','pkg://nuplan.planning.script.config.simulation','pkg://nuplan.planning.script.config.experiments'"
            },
            "args": [
                "+simulation=default_interplan_benchmark",
                "planner=pluto_planner",
                "scenario_builder=interplan",
                "scenario_filter=interplan10",
                "worker=sequential",
                "verbose=true",
                "experiment_uid=pluto_planner/interplan10",
                "planner.pluto_planner.render=false",
                "planner.pluto_planner.planner_ckpt=${workspaceFolder}/checkpoints/pluto_1M_aux_cil.ckpt",
                "+planner.pluto_planner.save_dir=null"
            ]
        }

error 

 MissingConfigException       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
In 'default_simulation': Could not find 'simulation/default_interplan_benchmark'

Available options in 'simulation':
	closed_loop_nonreactive_agents
	closed_loop_reactive_agents
	open_loop_boxes
	remote_closed_loop_nonreactive_agents
	remote_closed_loop_reactive_agents
	remote_open_loop_boxes
	validation_challenge
Config search path:
	provider=hydra, path=pkg://hydra.conf
	provider=main, path=file:///home/dataset/data/z00862936/DriveLLM-hw-0102_e2e/nuplan-devkit/nuplan/planning/script/config/simulation
	provider=hydra.searchpath in main, path=pkg://nuplan.planning.script.config.common
	provider=hydra.searchpath in main, path=pkg://nuplan.planning.script.experiments
	provider=schema, path=structured://
  File "/home/ma-user/.conda/envs/pluto/lib/python3.9/site-packages/hydra/_internal/defaults_list.py", line 801, in config_not_found_error
    raise MissingConfigException(
  File "/home/ma-user/.conda/envs/pluto/lib/python3.9/site-packages/hydra/_internal/defaults_list.py", line 485, in _create_defaults_tree_impl
    config_not_found_error(repo=repo, tree=root)
  File "/home/ma-user/.conda/envs/pluto/lib/python3.9/site-packages/hydra/_internal/defaults_list.py", line 517, in add_child
    subtree_ = _create_defaults_tree_impl(
  File "/home/ma-user/.conda/envs/pluto/lib/python3.9/site-packages/hydra/_internal/defaults_list.py", line 574, in _create_defaults_tree_impl
    add_child(children, new_root)
  File "/home/ma-user/.conda/envs/pluto/lib/python3.9/site-packages/hydra/_internal/defaults_list.py", line 280, in _expand_virtual_root
    subtree = _create_defaults_tree_impl(
  File "/home/ma-user/.conda/envs/pluto/lib/python3.9/site-packages/hydra/_internal/defaults_list.py", line 454, in _create_defaults_tree_impl
    return _expand_virtual_root(repo, root, overrides, skip_missing)
  File "/home/ma-user/.conda/envs/pluto/lib/python3.9/site-packages/hydra/_internal/defaults_list.py", line 355, in _create_defaults_tree
    ret = _create_defaults_tree_impl(
  File "/home/ma-user/.conda/envs/pluto/lib/python3.9/site-packages/hydra/_internal/defaults_list.py", line 717, in _create_defaults_list
    defaults_tree = _create_defaults_tree(
  File "/home/ma-user/.conda/envs/pluto/lib/python3.9/site-packages/hydra/_internal/defaults_list.py", line 747, in create_defaults_list
    defaults, tree = _create_defaults_list(
  File "/home/ma-user/.conda/envs/pluto/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 239, in _load_configuration_impl
    defaults_list = create_defaults_list(
  File "/home/ma-user/.conda/envs/pluto/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 141, in load_configuration
    return self._load_configuration_impl(
  File "/home/ma-user/.conda/envs/pluto/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 559, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/home/ma-user/.conda/envs/pluto/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 88, in run
    cfg = self.compose_config(
  File "/home/ma-user/.conda/envs/pluto/lib/python3.9/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/home/ma-user/.conda/envs/pluto/lib/python3.9/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/ma-user/.conda/envs/pluto/lib/python3.9/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/ma-user/.conda/envs/pluto/lib/python3.9/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/home/ma-user/.conda/envs/pluto/lib/python3.9/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/home/ma-user/wyn/pluto/run_simulation.py", line 109, in <module>
    main()
  File "/home/ma-user/.conda/envs/pluto/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ma-user/.conda/envs/pluto/lib/python3.9/runpy.py", line 197, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
hydra.errors.MissingConfigException: In 'default_simulation': Could not find 'simulation/default_interplan_benchmark'

**Available options in 'simulation':
	closed_loop_nonreactive_agents
	closed_loop_reactive_agents
	open_loop_boxes
	remote_closed_loop_nonreactive_agents
	remote_closed_loop_reactive_agents
	remote_open_loop_boxes
	validation_challenge
Config search path:
	provider=hydra, path=pkg://hydra.conf
	provider=main, path=file:///home/dataset/data/z00862936/DriveLLM-hw-0102_e2e/nuplan-devkit/nuplan/planning/script/config/simulation
	provider=hydra.searchpath in main, path=pkg://nuplan.planning.script.config.common
	provider=hydra.searchpath in main, path=pkg://nuplan.planning.script.experiments
	provider=schema, path=structured://**
