### ISSUE TITLE
Val14 mining, Val14

### ISSUE THREAD

**Issue by hanbinjang** [mh0797/interPlan#6]
Hello Marcel,

I have a few questions after reviewing the interPlan paper and code.

In Table 2 of the interPlan paper, val14 mining is compared with interPlan, and in Table 3, planning results are compared between val14 and interPlan. **Were the planning results in Table 3 also obtained using val14 mining?** If the comparison was indeed based on val14 mining, could you share the filter used for val14 mining?

In the results shown in Table 3, were the experiments in the val14 environment conducted using **closed-loop reactive agents**? Is it generally common to use **closed-loop reactive agents** for val14?

Thank you very much!

Best regards,
Hanbin.

**Comment by mh0797** [comment]
Hi @hanbinjang,

the results in table 3 refer to the complete (unfiltered) Val14 split, i.e. without mining.
We also used closed-loop reactive agents across all experiments.

In general, val14 is simply a standardized test split. You can use it with open-loop, closed-loop nonreactive and closed-loop reactive simulation. You can find it in tuplan_garage: https://github.com/autonomousvision/tuplan_garage

Best
Marcel
